### ISSUE TITLE
%broadcaster variable in EvalTwitchContext

### ISSUE THREAD

**Issue by herrhotzenplotz** [tsoding/kgbotka#170]
To default the `funny` command
e.g.: `addcmd funny %or(%broadcaster, %1) made a funny joke 0 times.`
should yield: 
+ in `#tsoding`:
  + `$funny` -> "Tsoding made a funny joke..."
  + `$funny aodhneine` -> "aodhneine made a funny joke..."
+ in `#foo`
  + `$funny` -> "Foo made a ...."

**Comment by rexim** [comment]
@herrhotzenplotz The easiest way to implement that is to use the channel name. If we gonna go that route it probably makes sense to even introduce `%channel` variable instead of `%broadcaster`. What do you think?

**Comment by herrhotzenplotz** [comment]
@rexim I was also thinking about `%channel`. So if that is the easier solution in your opinion, we should go for that name. :+1:

**Comment by rexim** [comment]
Usually there are three use case for the `!joke` command:

1. To target somebody: `!joke tsoding`
2. To make fun of the streamer in twitch chat: `!joke` (without arguments)
3. To make fun of the streamer on their Discord server: same as 2.

To address all of the three use cases we introduced the `%tchannel` variable (in #172) that contains the Twitch channel in the Twitch Context and an empty string in the Discord context.

It's supposed to be used like this: `%or(%1, %tchannel, "hardcoded name of the strimer")`.

- For use case 1 it picks `%1`
- For use case 2 it picks `%tchannel`
- For use case 3 it picks `"hardcoded name of the strimer"`

@herrhotzenplotz Is this solution good for you? Please close the issue if this works for you. Thanks!

**Comment by herrhotzenplotz** [comment]
@rexim This solution works for me so I will close this issue in the scope of #172 .
Thank you so much!
