### ISSUE TITLE
Add xkcd command to search for a particular xkcd comic

### ISSUE THREAD

**Issue by ghost** [tsoding/kgbotka#233]
It would be nice to have an `xkcd` command to which you can provide one (or several?) keywords and which would search the xkcd comics for that keyword.
For example, `xkcd compiling` should give https://xkcd.com/303/
Or, since it appears that each comic has a `transcript` div tag, these transcriptions could be searched for the keyword also and `xkcd -ass` might yield https://xkcd.com/37/.

**Comment by rexim** [comment]
@iv4nhoe does xkcd have some sort of API for that?

**Comment by ghost** [comment]
Not exactly, but there's a json interface. https://xkcd.com/json.html

**Comment by rexim** [comment]
@iv4nhoe how do we do it then? Build some sort of index manually? Sounds pretty tedious :thinking:

**Comment by ghost** [comment]
> how do we do it then? Build some sort of index manually?

I guess that's what would be needed to be done. I've searched a bit more and found there's https://relevant-xkcd.github.io to search xkcd comics. The source is on github too: https://github.com/adtac/relevant-xkcd, but it looks like they're maintaining an index of the comics too (not sure because I'm not too familiar with go).
> Sounds pretty tedious thinking

Fair enough, feel free to close the issue.

**Comment by rexim** [comment]
@iv4nhoe looks interesting. Thanks! I'll take a look into it!
